# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d741b1f81404756eb0747654e7a7f5c20e30d0c5ea6bc5e27cab35905b837190198021ab6ed6367bbc5e38a792f3826e348fbcea62fc2bb84e2c3c7747856f

test:
  secret_key_base: f7ab0c82fb1964b3a23b24d3df94819d3fb563a2a067efac72a76a59a778e8a182bc8df2f71e05cbe5324598c962a27b33d84b936a8fb623e8225f3633855872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
